# Generated by Django 6.0.3 on 2026-03-12 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
